# Generated by Django 2.0.6 on 2019-06-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_contact_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='reply',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
