# Generated by Django 2.0.6 on 2019-04-16 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0018_auto_20190309_1941'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('complete', 'Complete')], default='Requested', max_length=120)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.Unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
