# Generated by Django 2.0.6 on 2019-04-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliedunis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyapplication',
            name='admit_card',
            field=models.FileField(blank=True, upload_to='AdmitCards/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='applyapplication',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('processing', 'Processing'), ('complete', 'Complete')], default='Requested', max_length=120),
        ),
    ]
