# Generated by Django 2.0.6 on 2019-04-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliedunis', '0002_auto_20190424_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyapplication',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
