# Generated by Django 2.0.6 on 2019-05-16 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appliedunis', '0004_applyapplication_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyapplication',
            name='updated',
        ),
    ]
