# Generated by Django 2.0.6 on 2019-05-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliedunis', '0008_auto_20190528_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='application_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
