# Generated by Django 2.0.6 on 2019-05-28 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appliedunis', '0009_notification_application_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='application_id',
        ),
    ]
