# Generated by Django 2.0.6 on 2019-06-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliedunis', '0010_remove_notification_application_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyapplication',
            name='information',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
