# Generated by Django 2.0.6 on 2019-02-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190228_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinformation',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
