# Generated by Django 2.0.6 on 2019-02-28 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190228_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinformation',
            name='slug',
        ),
    ]
