# Generated by Django 2.0.6 on 2019-02-28 06:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0008_remove_studentinformation_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentInformation',
            new_name='UserProfile',
        ),
    ]
