# Generated by Django 2.0.6 on 2019-05-21 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20190521_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='higher_math',
        ),
    ]
