# Generated by Django 2.0.6 on 2019-04-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interestedunis', '0002_applieduni'),
    ]

    operations = [
        migrations.AddField(
            model_name='applieduni',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('processing', 'Porcessing'), ('applied', 'Applied')], default='requested', max_length=120),
        ),
    ]
