# Generated by Django 2.0.6 on 2019-04-24 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interestedunis', '0003_applieduni_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applieduni',
            name='units',
        ),
        migrations.RemoveField(
            model_name='applieduni',
            name='user',
        ),
        migrations.DeleteModel(
            name='AppliedUni',
        ),
    ]
