# Generated by Django 2.0.6 on 2019-06-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interestedunis', '0004_auto_20190424_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interesteduni',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
