# Generated by Django 2.0.6 on 2019-03-08 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='slug',
        ),
    ]
