# Generated by Django 2.0.6 on 2019-03-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_auto_20190308_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='short_form',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
