# Generated by Django 2.0.6 on 2019-03-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0006_department_short_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='short_form',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
