# Generated by Django 2.0.6 on 2019-03-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0007_auto_20190308_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='required_gpa_hsc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='required_gpa_ssc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
