# Generated by Django 2.0.6 on 2019-03-09 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0008_auto_20190309_0857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='required_gpa_hsc',
            new_name='required_gpa_each',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='required_gpa_ssc',
        ),
    ]
