# Generated by Django 2.0.6 on 2019-03-09 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0009_auto_20190309_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(blank=True, max_length=255, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('depts', models.ManyToManyField(blank=True, to='universities.Department')),
                ('uni_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='universities.University')),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
            },
        ),
    ]
