# Generated by Django 2.0.6 on 2019-03-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0010_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
