# Generated by Django 2.0.6 on 2019-03-09 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0011_department_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='slug',
        ),
    ]
