# Generated by Django 2.0.6 on 2019-03-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0012_remove_department_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
