# Generated by Django 2.0.6 on 2019-03-09 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0014_auto_20190309_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='slug',
        ),
    ]
