# Generated by Django 2.0.6 on 2019-03-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0015_remove_department_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
