# Generated by Django 2.0.6 on 2019-03-09 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0016_department_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='slug',
            new_name='dept_slug',
        ),
    ]
