# Generated by Django 2.0.6 on 2019-04-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0018_auto_20190309_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='short_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
