# Generated by Django 2.0.6 on 2019-05-01 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0019_university_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_start', models.DateTimeField()),
                ('apply_end', models.DateTimeField()),
                ('valid_list', models.DateTimeField()),
                ('result_pub', models.DateTimeField()),
                ('admit_dwon_start', models.DateTimeField()),
                ('admit_dwon_end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_edu', models.IntegerField(blank=True, null=True)),
                ('research_innovation', models.IntegerField(blank=True, null=True)),
                ('tuition_fee', models.IntegerField(blank=True, null=True)),
                ('extra_curricular', models.IntegerField(blank=True, null=True)),
                ('living', models.IntegerField(blank=True, null=True)),
                ('transport', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='unit',
            name='exam_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='established',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='notice',
            field=models.FileField(blank=True, upload_to='Admissoin Notice/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='university',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='uni_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.University'),
        ),
        migrations.AddField(
            model_name='applyschedule',
            name='uni_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.University'),
        ),
    ]
