# Generated by Django 2.0.6 on 2019-05-01 13:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0020_auto_20190501_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
