# Generated by Django 2.0.6 on 2019-05-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0021_auto_20190501_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
