# Generated by Django 2.0.6 on 2019-05-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0022_auto_20190502_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyschedule',
            name='admit_dwon_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='applyschedule',
            name='admit_dwon_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='applyschedule',
            name='apply_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='applyschedule',
            name='apply_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='applyschedule',
            name='result_pub',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='applyschedule',
            name='valid_list',
            field=models.DateTimeField(null=True),
        ),
    ]
