# Generated by Django 2.0.6 on 2019-05-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0023_auto_20190503_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='notice',
        ),
        migrations.AddField(
            model_name='applyschedule',
            name='notice',
            field=models.FileField(blank=True, upload_to='Admissoin Notice/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='university',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='category',
            field=models.CharField(blank=True, choices=[('agriculteral', 'Agrecultural'), ('engineering', 'Engineering'), ('science-&-technology', 'Science-&-Technology'), ('medical', 'Medical'), ('textile', 'Textile'), ('general', 'General')], max_length=120, null=True),
        ),
    ]
