# Generated by Django 2.0.6 on 2019-05-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0024_auto_20190506_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyschedule',
            name='admit_dwon_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applyschedule',
            name='admit_dwon_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applyschedule',
            name='apply_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applyschedule',
            name='apply_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applyschedule',
            name='result_pub',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applyschedule',
            name='valid_list',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
