# Generated by Django 2.0.6 on 2019-05-17 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0027_auto_20190517_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='about',
        ),
    ]
