# Generated by Django 2.0.6 on 2019-05-18 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0028_remove_faculty_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='depts',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='apply_dead',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='subject',
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='universities.Faculty'),
        ),
    ]
