# Generated by Django 2.0.6 on 2019-05-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0030_unit_apply_dead'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='arts_gpa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='unit',
            name='arts_tgpa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='unit',
            name='ban_gpa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='unit',
            name='bio_gpa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='unit',
            name='chem_gpa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='unit',
            name='commerce_gpa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='unit',
            name='commerce_tgpa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='unit',
            name='en_gpa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='unit',
            name='group',
            field=models.CharField(blank=True, choices=[('science', 'Science'), ('commerce', 'Commerce'), ('humanities', 'Humanities')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='hsc_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='math_gpa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='unit',
            name='phy_gpa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='unit',
            name='science_gpa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='unit',
            name='science_tgpa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='unit',
            name='ssc_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='tgpa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
