# Generated by Django 2.0.6 on 2019-05-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0033_auto_20190524_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='apply_fees',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
