# Generated by Django 2.0.6 on 2019-05-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0034_auto_20190524_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='short_name',
        ),
        migrations.AddField(
            model_name='university',
            name='logo',
            field=models.FileField(blank=True, upload_to='Logo/'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='group',
            field=models.CharField(blank=True, choices=[('----------', '----------'), ('science', 'Science'), ('commerce', 'Commerce'), ('humanities', 'Humanities')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='category',
            field=models.CharField(blank=True, choices=[('----------', '----------'), ('agricultural', 'Agrecultural'), ('engineering', 'Engineering'), ('science', 'Science & Technology'), ('medical', 'Medical'), ('general', 'General')], max_length=120, null=True),
        ),
    ]
