# Generated by Django 2.0.6 on 2019-05-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0035_auto_20190526_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='unit',
            name='group',
        ),
        migrations.AddField(
            model_name='unit',
            name='group',
            field=models.ManyToManyField(blank=True, to='universities.Group'),
        ),
    ]
