# Generated by Django 2.0.6 on 2019-05-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0039_auto_20190529_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='groups',
        ),
        migrations.AddField(
            model_name='unit',
            name='commerce',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='humanities',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='science',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
