# Generated by Django 2.0.6 on 2019-06-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0041_auto_20190530_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='average',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='rating',
            name='extra_curricular',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='rating',
            name='living',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='rating',
            name='quality_edu',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='rating',
            name='research_innovation',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='rating',
            name='transport',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='rating',
            name='tuition_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
