# Generated by Django 2.0.6 on 2019-06-19 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0042_auto_20190619_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='average',
        ),
    ]
