# Generated by Django 2.0.6 on 2019-06-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0053_auto_20190619_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='arts_gpa',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='arts_tgpa',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='ban_gpa',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='bio_gpa',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='chem_gpa',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='commerce_gpa',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='commerce_tgpa',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='en_gpa',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='math_gpa',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='phy_gpa',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='science_gpa',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='science_tgpa',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='tgpa',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='category',
            field=models.CharField(blank=True, choices=[('----------', '----------'), ('agricultural', 'Agrecultural'), ('engineering', 'Engineering'), ('science', 'Science & Technology'), ('medical', 'Medical'), ('general', 'General'), ('textile', 'Textile')], max_length=120, null=True),
        ),
    ]
