# Generated by Django 2.0.6 on 2019-07-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0054_auto_20190619_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='notice',
            field=models.FileField(blank=True, upload_to='Admissoin Notice/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='unit',
            name='result',
            field=models.FileField(blank=True, upload_to='Admissoin Notice/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='unit',
            name='seat_plan',
            field=models.FileField(blank=True, upload_to='Admissoin Notice/%Y/%m/%d'),
        ),
    ]
